service: text-to-speech

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - polly:SynthesizeSpeech
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - 's3:PutObject'
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - 'dynamodb:PutItem'
      Resource: "*"

            
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
        

plugins:
  - serverless-webpack


package:
    individually: true

custom:
  tableName: text-to-speech-db
  bucketName: text-to-speech-bucket-87432

functions:
  hello:
    handler: handler.hello
  create-speech:
    handler: lambdas/create-speech.handler
    events:
      - sns: create_speech

resources:
  Resources:
    SpeechBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    TextToSpeechTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST