service: text-to-speech

frameworkVersion: '2'

provider:
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
    voiceId: Joanna
    snsTopicArn: arn:aws:sns:us-east-1:791415850326:create_speech

  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - polly:SynthesizeSpeech
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - 's3:PutObject'
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - 'SNS:Publish'
      Resource: "*"

plugins:
  - serverless-webpack

package:
    individually: true

custom:
  tableName: text-to-speech-db
  bucketName: text-to-speech-bucket-87432

functions:
  create-speech:
    handler: lambdas/create-speech.handler
    events:
      - sns: create_speech
  get-speech:
    handler: lambdas/get-speech.handler
    events:
      - http:
          path: get_speech
          method: GET
          cors: true
  create-speech-api:
    handler: lambdas/create-speech-api.handler
    events:
      - http:
          path: create_speech
          method: POST
          cors: true

resources:
  Resources:
    SpeechBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    TextToSpeechTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST